name: Build and Push Docker image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Log in Docker Hub
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login https://index.docker.io/v1/ --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - uses: actions/checkout@v4
      - name: Build and tag image
        run: |
          docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/ubuntu:latest

      - name: Push image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/ubuntu:latest
  
